name: voila
channels:
  - conda-forge
dependencies:
  - geojson
  - geopy
  - ipyvolume
  - bqplot
  - scipy
  - voila=0.1.7
  - ipyleaflet>=0.11.0
  - ipympl
  - reportlab>=3.5.23
  - svglib=>0.9.1
  - xleaflet=0.8.0
  - xeus-cling=0.6.0
  - pip:
    - "-r requirements.txt"
