name: voila
channels:
  - conda-forge
dependencies:
  - geojson
  - geopy
  - ipyvolume
  - bqplot
  - scipy
  - ipympl
  - voila=0.1.3
  - ipyleaflet
  - ipympl
  - xleaflet=0.7.0
  - xeus-cling=0.5.1
